name: Chakra-View
favicon: null
layout_spectrum: 0.9004617345053703
typography_spectrum: 0.41066381824202836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4437546406406909
  lightness: 0.7604201501235366
  saturation: 0.25116318743675947
  rhythmicContrast: 0.6180186965502799
purpose: []
