analytics: {}
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.644736
  lightness: 0.51398
  rhythmicContrast: 0.511513
  saturation: 0.412006
cta: {}
layout_spectrum: 0.9004617345053703
name: Chakra-View
opengraph: {}
purpose: []
typography_spectrum: 0.41066381824202836
